name : Build and Deploy to EC2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  AUUTO_DEPLOY:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run scripts in server
      - uses: actions/checkout@v2

      - name: Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run scripts in server
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          timeout: 40s
          script: ${{ secrets.SCRIPT }}
